library
  mica keywords
  export
    of
    nonempty
    digit
    alphabetic
    numeric
    whitespace
    negative
    positive
    nonnegative
    nonpositive
    integer
    char/eof
    nothing
    separated
  import leo scheme

  define-keywords
    of
    nonempty
    digit
    alphabetic
    numeric
    whitespace
    negative
    positive
    nonnegative
    nonpositive
    integer
    char/eof
    nothing
    separated
