library
  mica typed keywords
  export:
    type
    boolean, integer
    native, overflowing
    unsigned, signed, wide
    char, short, int, long
    size
    float, double
    struct, array, bits
  import
    mica typed base

  define-keywords
    type
    boolean, integer
    native, overflowing
    unsigned, signed, wide
    char, short, int, long
    size
    float, double
    struct, array, bits
